version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      
# docker-compose run web django-admin startproject composeexample .
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'HOST': 'db',
#         'PORT': 5432,
#     }
# }

# ALLOWED_HOSTS = ["CHAR ip"]

# docker-compose up

# where can i run "python manage.py migrate" ?
