version: '3'


services:
  web:
    build: .
    container_name: flask_app
    tty: true
    volumes:
      - ./app/:/app
    ports:
      - "5001:5000"
    restart: always
    command: python app.py

  proxy:
    container_name: nginx_app
    image: "nginx:stable"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    env_file:
      - .env
    links:       
      - web