version: '3'


services:
  web:
    build: .
    container_name: flask_app
    tty: true
    volumes:
      - ./app/:/app
    ports:
      - "5001:5000"
    restart: always
    command: python app.py
  # proxy:
